"""Step V2: attach every BQ figure to the passage it answers, and build the board.

Reads `outputs/visual_questions.json` (written by make_visual_layer.py) and, for
each figure, inserts a question/answer/figure block into the documents named in
its anchors. Blocks are delimited by HTML comments, so a re-run replaces them
instead of duplicating them - the documents stay hand-editable everywhere else.

Two anchor modes:
  after_heading   insert at the END of that section (before the next heading of
                  the same or a higher level), so the figure follows the prose it
                  illustrates
  after_match     insert directly after the first line containing the key, for
                  paragraph-level precision

A missing anchor is a hard error: silent drift between a figure and the text it
claims to illustrate is the failure this step exists to prevent.

Also writes `docs/visual-decision-board.md`: all 26 questions, answers and
figures in one place, for reading rather than auditing.

Run:  python src/analysis/embed_figures.py [--check]
"""
from __future__ import annotations

import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CONTRACT = ROOT / "outputs" / "visual_questions.json"
BOARD = ROOT / "docs" / "visual-decision-board.md"

START = "<!-- {cid}:start (figure generated by src/analysis/make_visual_layer.py - do not edit by hand) -->"
END = "<!-- {cid}:end -->"
BLOCK_RE = r"<!-- {cid}:start.*?-->\n.*?<!-- {cid}:end -->\n?"


def relative_figure_path(doc: str, filename: str) -> str:
    depth = len(Path(doc).parent.parts) if Path(doc).parent != Path(".") else 0
    return "../" * depth + f"outputs/figures/{filename}"


def block_for(fig: dict, doc: str) -> str:
    cid = fig["chart_id"]
    path = relative_figure_path(doc, fig["png"])
    caveat = f" **Read with:** {fig['caveat']}" if fig.get("caveat") else ""
    return (
        START.format(cid=cid) + "\n"
        f"**Q. {fig['question']}**\n\n"
        f"{fig['answer']}\n\n"
        f"[![{cid}]({path})]({path})\n\n"
        f"<sub>**Figure {cid.split('_')[0]}** · {fig['relationship']} shown as `{fig['mark']}` "
        f"({fig['data_signature']}) · built from `{'`, `'.join(fig['tables'])}` · "
        f"units: {fig['units']}.{caveat}</sub>\n"
        + END.format(cid=cid) + "\n"
    )


def strip_existing(text: str, cid: str) -> str:
    return re.sub(BLOCK_RE.format(cid=re.escape(cid)), "", text, flags=re.S)


def masked_lines(lines: list[str]) -> list[bool]:
    """True where a line sits inside a generated block (never anchor into one)."""
    inside, mask = False, []
    for line in lines:
        if re.match(r"<!-- BQ\d+\w*:start", line):
            inside = True
        mask.append(inside)
        if re.match(r"<!-- BQ\d+\w*:end -->", line):
            inside = False
    return mask


def heading_level(line: str) -> int | None:
    match = re.match(r"^(#{1,6})\s", line)
    return len(match.group(1)) if match else None


def insertion_index(lines: list[str], mode: str, key: str) -> int | None:
    mask = masked_lines(lines)
    if mode == "after_heading":
        for i, line in enumerate(lines):
            if mask[i] or line.strip() != key.strip():
                continue
            level = heading_level(line)
            if level is None:
                continue
            for j in range(i + 1, len(lines)):
                nxt = heading_level(lines[j])
                if nxt is not None and nxt <= level and not mask[j]:
                    return j
            return len(lines)
        return None
    if mode == "after_match":
        for i, line in enumerate(lines):
            if not mask[i] and key in line:
                return i + 1
        return None
    raise ValueError(f"unknown anchor mode: {mode}")


def embed(figures: list[dict], *, check_only: bool = False) -> list[str]:
    by_doc: dict[str, list[tuple[dict, str, str]]] = {}
    for fig in figures:
        for anchor in fig["anchors"]:
            doc, mode, key = anchor
            by_doc.setdefault(doc, []).append((fig, mode, key))

    problems: list[str] = []
    for doc, items in sorted(by_doc.items()):
        path = ROOT / doc
        if not path.exists():
            problems.append(f"{doc}: document does not exist")
            continue
        text = path.read_text(encoding="utf-8")
        for fig, _, _ in items:
            text = strip_existing(text, fig["chart_id"])
        for fig, mode, key in sorted(items, key=lambda it: it[0]["chart_id"]):
            lines = text.splitlines(keepends=True)
            index = insertion_index(lines, mode, key)
            if index is None:
                problems.append(f"{doc}: anchor not found ({mode}) -> {key!r} [{fig['chart_id']}]")
                continue
            block = "\n" + block_for(fig, doc) + "\n"
            lines.insert(index, block)
            text = "".join(lines)
        text = re.sub(r"\n{4,}", "\n\n\n", text)
        if not check_only:
            path.write_text(text, encoding="utf-8")
    return problems


def write_board(payload: dict) -> None:
    figures = payload["figures"]
    lines = [
        "# Visual decision board",
        "",
        "Every finding in this project that bears on a decision, stated as the question it answers, "
        "with the chart that answers it. The questions are the owner's own "
        "(`config/profile.json`: twenty years of marketing and growth work, based in Graz, German at "
        "A2-B1, moving towards data roles); a different reader would ask different ones of the same "
        "tables.",
        "",
        f"**Vintage.** {payload['data_vintage']}. Regenerate with `python src/analysis/make_visual_layer.py` "
        "then `python src/analysis/embed_figures.py`.",
        "",
        "**How to read these.** Every answer sentence below is computed from the named table when the "
        "figure is rendered, so a caption cannot drift away from the data. Every chart names its "
        "relationship and its mark from the GSD-DSX chart catalogue, carries its own n, units and "
        "source, and shows an interval wherever it shows an estimate. Shares are shares of "
        "advertisements that *mention* something, never of jobs that require it; nothing here "
        "measures hiring.",
        "",
        "| # | Question | Answer in one line | Chart |",
        "|---|---|---|---|",
    ]
    for fig in figures:
        short = fig["chart_id"].split("_")[0]
        answer = fig["answer"].replace("|", "/")
        question = fig["question"].replace("|", "/")
        lines.append(f"| [{short}](#{fig['chart_id'].lower().replace('_', '-')}) | {question} | {answer} "
                     f"| `{fig['mark']}` |")
    lines += ["", "---", ""]
    for fig in figures:
        cid = fig["chart_id"]
        anchors = ", ".join(f"`{doc}`" for doc, _, _ in fig["anchors"])
        lines += [
            f"## {cid}",
            "",
            f"**Q. {fig['question']}**",
            "",
            fig["answer"],
            "",
            f"[![{cid}](../outputs/figures/{fig['png']})](../outputs/figures/{fig['png']})",
            "",
            f"*Relationship:* {fig['relationship']} · *mark:* `{fig['mark']}` ({fig['data_signature']}) · "
            f"*units:* {fig['units']}",
            "",
            f"*Built from:* `{'`, `'.join(fig['tables'])}`",
            "",
            f"*Read with:* {fig['caveat']}" if fig.get("caveat") else "",
            "",
            f"*Attached in:* {anchors}",
            "",
        ]
    BOARD.write_text("\n".join(line for line in lines) + "\n", encoding="utf-8")


def main() -> None:
    check_only = "--check" in sys.argv
    payload = json.loads(CONTRACT.read_text(encoding="utf-8"))
    problems = embed(payload["figures"], check_only=check_only)
    if not check_only:
        write_board(payload)
        print(f"board -> {BOARD.relative_to(ROOT)}")
    docs = {doc for fig in payload["figures"] for doc, _, _ in fig["anchors"]}
    print(f"{len(payload['figures'])} figures attached across {len(docs)} documents")
    if problems:
        for problem in problems:
            print(f"  UNRESOLVED {problem}", file=sys.stderr)
        raise SystemExit(f"{len(problems)} anchor(s) unresolved")


if __name__ == "__main__":
    main()
